version: '3.3'
services:

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/log/data
    ports:
      - 5050:80
    env_file:
      - ./env/pgadmin.env
    restart: unless-stopped

  backend:
    build: ./backend/
    ports:
      - 80:80

volumes:
  postgres:
  pgadmin: